### ISSUE TITLE
[checklist] Feature migration to V1

### ISSUE THREAD

**Issue by whisperity** [whisperity/envprobe#16]
The full list of Envprobe's features that exist and should either be migrated to the new version or cut out. All migrated features should be tested #8!

- [x] Shell hooking, control generation
  - [x] Bash implementation
  - [x] Zsh implementation
  - [x] `(epc) shell` command
  - [x] Cleanup of files for exiting shells (#11)
- [x] `vartypes` - environment variable mapping to Pythonic types
  - [x] Built-in heuristics for mapping a variable to such a type
- [x] Understanding of environment and difference
  - [x] Per-shell persistency
  - [x] Environment loading
  - [x] Difference between current and persisted
- [x] Environment management commands:
  - [x] `get`
  - [x] `set`
  - [x] `add`
  - [x] `remove`
  - [x] `undefine`
  - [x] Proper shortcut handling for these
- [x] Configuration file handling
- [x] Variable tracking
  - [X] Tracking configuration, two-level tracking overlay
  - [x] `(epc) track`, `(epc) default-tracking` commands to control this configuration
- [x] Saved configurations
  - [x] Difference persistency (properly? #2)
  - [x] Respecting the *tracking* settings
  - [x] `diff`
  - [X] `save`
  - [x] `load`
  - [x] `list`, `delete`
- [x] User-configured `vartypes` heuristics settings: `(epc) set-type`
- [x] Community description features
  - [X] Setting description locally: `(epc) set-description`
  - [X] `(epc) update-community`
  - [x] Respecting the downloaded community descriptions when resolving variable type.

**Comment by whisperity** [comment]
Sh\*t... Well this `v1` release is still not done because there are some `PYTHONPATH` magicks I was unable to work around with until now...

**Comment by whisperity** [comment]
Okay, I think this is now properly fixed and **`v1`**'s development is almost at its conclusion! Just need to try it in production for a little while...
